package dk.skancode.skanmate.data.model

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

object ColumnTypeSerializer: KSerializer<ColumnType> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor(
        "dk.skancode.skanmate.ColumnType",
        PrimitiveKind.STRING,
    )

    override fun serialize(
        encoder: Encoder,
        value: ColumnType
    ) {
        encoder.encodeString(value.t)
    }

    override fun deserialize(decoder: Decoder): ColumnType {
        return ColumnType.from(decoder.decodeString())
    }
}

@Serializable(with = ColumnTypeSerializer::class)
sealed class ColumnType(val t: ColumnDTOType, val autogenerated: kotlin.Boolean) {
    data object Text: ColumnType(TEXT_COLUMN, false)
    data object Numeric: ColumnType(NUMERIC_COLUMN, false)
    data object Boolean: ColumnType(BOOLEAN_COLUMN, false)
    data object File: ColumnType(FILE_COLUMN, false)
    data object List: ColumnType(LIST_COLUMN, false)
    data object GPS: ColumnType(GPS_COLUMN, false)
    data object Id: ColumnType(ID_COLUMN, true)
    data object User: ColumnType(USER_COLUMN, true)
    data object Timestamp: ColumnType(TIMESTAMP_COLUMN, true)
    data object Unknown: ColumnType(UNKNOWN_COLUMN, true)

    companion object {
        private val map: Map<ColumnDTOType, ColumnType> = mutableMapOf(
            TEXT_COLUMN to Text,
            NUMERIC_COLUMN to Numeric,
            BOOLEAN_COLUMN to Boolean,
            FILE_COLUMN to File,
            ID_COLUMN to Id,
            USER_COLUMN to User,
            TIMESTAMP_COLUMN to Timestamp,
            LIST_COLUMN to List,
            GPS_COLUMN to GPS,
            UNKNOWN_COLUMN to Unknown,
        )

        fun from(dto: ColumnDTOType): ColumnType {
            return map[dto] ?: Unknown
        }
    }
}

private typealias ColumnDTOType = String
private const val TEXT_COLUMN: ColumnDTOType = "TEXT"
private const val NUMERIC_COLUMN: ColumnDTOType = "NUMERIC"
private const val BOOLEAN_COLUMN: ColumnDTOType = "BOOLEAN"
private const val FILE_COLUMN: ColumnDTOType = "FILE"
private const val ID_COLUMN: ColumnDTOType = "ID"
private const val USER_COLUMN: ColumnDTOType = "USER"
private const val TIMESTAMP_COLUMN: ColumnDTOType = "TIMESTAMP"
private const val LIST_COLUMN: ColumnDTOType = "LIST"
private const val GPS_COLUMN: ColumnDTOType = "GPS"
private const val UNKNOWN_COLUMN: ColumnDTOType = "UNKNOWN"
